# Copyright (C) 2019 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2019-03-03

version: '2.3'

# These services run on Apollo (Intel Core).
services:
    ###########################################################################
    # opendlv-vehicle-view on 102.
    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.57
        cpuset: "1"
        restart: always
        network_mode: "host"
        volumes:
        - /mnt/hdd/recordings:/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=102
        - PLAYBACK_OD4SESSION_CID=202
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Voyager
        ports:
        - "8081:8081"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 node index.js"
        runtime: runc


    ###########################################################################
    # CAN interface to receive GPS/IMU data.
    dlv-can-peak:
        container_name: dlv-can-peak
        image: chalmersrevere/opendlv-device-gps-peak-multi:v0.0.4
        cpuset: "2"
        restart: always
        network_mode: "host"
        privileged: true
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 /usr/bin/opendlv-device-gps-pos --cid=102 --can=can0"
        runtime: runc

