# Copyright (C) 2019 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2019-06-04

version: '2.3'

# These services run on Apollo (Intel Core).
services:
    ###########################################################################
    # Dump all containers from CID 106 on request.
    record-106:
        container_name: record-106
        image: chrberger/cluon-record-multi:v0.0.1
        cpuset: "1"
        restart: always
        network_mode: "host"
        volumes:
        - $HOME/recordings/upload:/recordings
        working_dir: /recordings
        command: "--remote --recsuffix=-all-no-can --cid=106"
        runtime: runc

    ###########################################################################
    # CAN interface to receive GPS/IMU data.
    dlv-can-peak:
        container_name: dlv-can-peak
        image: chalmersrevere/opendlv-device-gps-peak-amd64:v2.0.0
        cpuset: "2"
        restart: always
        network_mode: "host"
        privileged: true
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 /usr/bin/opendlv-device-gps-peak --cid=106 --can=vcan1"
        #command: "nice -n -1 /usr/bin/opendlv-device-gps-peak --cid=106 --can=can0"
        runtime: runc

        # vcan1 is PEAK GPS with no lat/lon/speed

    # Temporary fix to use data from Garmin
    relay-from-99:
        container_name: relay-from-99
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "1"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -6 /usr/bin/cluon-relay --cid-from=99 --cid-to=106 --keep=19"
        runtime: runc

    ###########################################################################
    # Raw CAN interfaces to the truck.
    dlv-can-raw:
        container_name: dlv-can-raw
        image: chalmersrevere/opendlv-device-can-raw-multi:v0.0.3
        cpuset: "3"
        restart: always
        network_mode: "host"
        privileged: true
        volumes:
        - $HOME/recordings/upload:/recordings
        working_dir: /recordings
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 /usr/bin/opendlv-device-can-raw --can-channels=can1:1,can2:2,can3:3 --remote --recsuffix=-can --cid=106"
        runtime: runc

