# Copyright (C) 2019 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2019-03-24

version: '2.3'

# These services run on Apollo (Intel Core).
services:
    ###########################################################################
    # opendlv-vehicle-view on 105.
    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.60
        cpuset: "1"
        restart: always
        network_mode: "host"
        volumes:
        - /mnt/hdd/recordings:/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=105
        - PLAYBACK_OD4SESSION_CID=205
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Voyager
        ports:
        - "8081:8081"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 node index.js"
        runtime: runc


    ###########################################################################
    # Relay and downsample Envelopes from CID 106 (local CID session) to CID 105 (for opendlv-vehicle-view).
    relay-downsample-106-105:
        container_name: relay-downsample-106-105
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "2"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/cluon-relay --cid-from=106 --cid-to=105 --downsample=19:10,1046:10"
        runtime: runc

    ###########################################################################
    # Relay cluon.data.RecorderCommand.
    relay-recordercommand-105-106:
        container_name: relay-recordercommand-105-106
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "2"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/cluon-relay --cid-from=105 --cid-to=106 --keep=11"
        runtime: runc

    ###########################################################################
    # Dump all containers from CID 106 on request.
    record-106:
        container_name: record-106
        image: chrberger/cluon-record-multi:v0.0.1
        cpuset: "2"
        restart: always
        network_mode: "host"
        volumes:
        - $HOME/recordings:/recordings
        working_dir: /recordings
        command: "--remote --recsuffix=-all --cid=106"
        runtime: runc


    ###########################################################################
    # CAN interface to receive GPS/IMU data.
    dlv-can-peak:
        container_name: dlv-can-peak
        image: chalmersrevere/opendlv-device-gps-peak-multi:v0.0.8
        cpuset: "3"
        restart: always
        network_mode: "host"
        privileged: true
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 /usr/bin/opendlv-device-gps-peak --cid=106 --can=can2"
        runtime: runc

