# Copyright (C) 2019 Christian Berger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# Date: 2019-05-16

version: '2.3'

# These services run on Apollo (Intel Core).
services:
    ###########################################################################
    # opendlv-vehicle-view on 105.
    vehicle-view:
        container_name: opendlv-vehicle-view
        image: chalmersrevere/opendlv-vehicle-view-multi:v0.0.60
        cpuset: "1"
        restart: always
        network_mode: "host"
        volumes:
        - $HOME/recordings/lossy:/opt/vehicle-view/recordings
        - /var/run/docker.sock:/var/run/docker.sock
        environment:
        - OD4SESSION_CID=105
        - PLAYBACK_OD4SESSION_CID=205
        - OPENDLV_VEHICLE_VIEW_PLATFORM=Snowfox
        ports:
        - "8081:8081"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 node index.js"
        runtime: runc


    ###########################################################################
    # Relay and downsample Envelopes from CID 106 (local CID session) to CID 105 (for opendlv-vehicle-view).
    relay-downsample-106-105:
        container_name: relay-downsample-106-105
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "2"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -5 /usr/bin/cluon-relay --cid-from=106 --cid-to=105 --downsample=19:10,1046:10"
        runtime: runc

    ###########################################################################
    # Relay cluon.data.RecorderCommand.
    relay-recordercommand-105-106:
        container_name: relay-recordercommand-105-106
        image: chrberger/cluon-relay-multi:v0.0.4
        cpuset: "2"
        restart: always
        network_mode: "host"
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/cluon-relay --cid-from=105 --cid-to=106 --keep=11"
        runtime: runc

    ###########################################################################
    # Dump all containers from CID 106 on request.
    record-106:
        container_name: record-106
        image: chrberger/cluon-record-multi:v0.0.1
        cpuset: "2"
        restart: always
        network_mode: "host"
        volumes:
        - $HOME/recordings/upload:/recordings
        working_dir: /recordings
        command: "--remote --recsuffix=-all --cid=106"
        runtime: runc


    ###########################################################################
    # CAN interface to receive GPS/IMU data.
    dlv-can-peak:
        container_name: dlv-can-peak
        image: chalmersrevere/opendlv-device-gps-peak-amd64:v2.0.0
        cpuset: "3"
        restart: always
        network_mode: "host"
        privileged: true
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -1 /usr/bin/opendlv-device-gps-peak --cid=106 --can=can0"
        runtime: runc

    ###########################################################################
    # Axis camera including recording functionality with remote start/stop.
    dev-camera-axis0:
        container_name: dev-camera-axis0
        image: chalmersrevere/opendlv-device-camera-mjpegoverhttp-multi:v0.0.3
        cpuset: "6"
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /mnt/Volume1/data:/tmp
        - $HOME/recordings/lossless:/recordings
        working_dir: /recordings
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -8 /usr/bin/opendlv-device-camera-mjpegoverhttp --url=http://10.40.41.2/axis-cgi/mjpg/video.cgi\\?channel=0\\&.mjpg\\&compression=0 --width=1280 --height=720 --name.i420=axis0.i420 --name.argb=axis0.argb --remote --recsuffix=-axis0-jpeg --skip.argb --cid=106 --id=0"
        runtime: runc

    i420toolbox:
        container_name: i420toolbox
        image: chalmersrevere/i420toolbox-multi:v0.0.2
        cpuset: "6"
        restart: always
        depends_on:
        - dev-camera-axis0
        ipc: "host"
        volumes:
        - /mnt/Volume1/data:/tmp
        command: "--in=axis0.i420 --in.width=1280 --in.height=720 --crop.x=320 --crop.y=120 --crop.width=640 --crop.height=480 --out=axisds0.i420"

    video-h264-encoder-amd64:
        container_name: h264enc
        build:
            context: https://github.com/chalmers-revere/opendlv-video-h264-encoder.git#v0.0.2
            dockerfile: Dockerfile.amd64
        restart: always
        cpuset: "6"
        depends_on:
        - dev-camera-axis0
        - i420toolbox
        network_mode: "host"
        ipc: "host"
        volumes:
        - /mnt/Volume1/data:/tmp
        command: "--name=axisds0.i420 --width=640 --height=480 --bitrate=4895294 --bitrate_max=5000000 --gop=1 --rc_mode=1 --ecomplexity=2 --sps_pps_strategy=6 --num_ref_frame=11 --ssei=1 --prefix_nal=1 --entropy_coding=0 --frame_skip=0 --qp_max=38 --qp_min=17 --long_term_ref=0 --loop_filter=0 --denoise=1 --background_detection=0 --adaptive_quant=0 --frame_cropping=1 --scene_change_detect=1 --padding=1 --cid=105 --id=0"

    vp9-axis0:
        container_name: vp9-axis0
        image: vp9:v0.0.7
        depends_on:
        - dev-camera-axis0
        cpuset: "5"
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /mnt/Volume1/data:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/opendlv-video-vpx-encoder --name=axis0.i420 --width=1280 --height=720 --vp8 --gop=100 --cpu_used=6 --bitrate=600000 --cid=106 --id=3 --verbose"

    ###########################################################################
    # Left PtGrey camera.
    device-camera-ptgrey-amd64-left:
        container_name: dlv-ptgrey-left
        image: ptgrey:v3
        #build:
        #    context: https://github.com/chalmers-revere/opendlv-device-camera-spinnaker.git
        #    dockerfile: Dockerfile.amd64
        cpuset: "7"
        restart: always
        network_mode: "host"
        ipc: "host"
        volumes:
        - /mnt/Volume1/data:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -8 /usr/bin/opendlv-device-camera-spinnaker --camera=19074537 --width=2048 --height=1536 --fps=15 --name.i420=ptg-left.i420 --name.argb=ptg-left.argb --nocameratimestamp"

    qsv-h264-thumbnail-ptgrey-left:
        container_name: qsv-h264-thumbnail-ptgrey-left
        image: qsv:latest
        depends_on:
        - device-camera-ptgrey-amd64-left
        cpuset: "8"
        devices:
        - /dev/dri/renderD128
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /mnt/Volume1/data:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/video-qsv-h264-encoder --name=ptg-left.i420 --width=2048 --height=1536 --bitrate=3000 --crop.x=704 --crop.y=500 --crop.width=640 --crop.height=480 --downsample=2 --cid=105 --id=1"
        runtime: runc

    nvenc-h264-ll-rec-ptgrey-left:
        container_name: nvenc-h264-ll-rec-ptgrey-left
        #image: chrberger/video-nvenc-h264-recorder-amd64:cuda10-v0.0.2
        image: nvenc-h264:v2
        depends_on:
        - device-camera-ptgrey-amd64-left
        cpuset: "9"
        init: true
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /mnt/Volume1/data:/tmp
        - $HOME/recordings/lossless:/recordings
        - /usr/lib64/libnvcuvid.so.418.56:/usr/lib/x86_64-linux-gnu/libnvcuvid.so.418.56
        - /usr/lib64/libnvidia-encode.so.418.56:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.418.56
        working_dir: /recordings
        command: "--name=ptg-left.i420 --width=2048 --height=1536 --recsuffix=-ptgrey-left-lossless --remote --cid=106 --id=1"
        runtime: nvidia

    qsv-vp9-ptgrey-left:
        container_name: qsv-vp9-left
        image: qsv-vp9:v0.0.1
        depends_on:
        - device-camera-ptgrey-amd64-left
        cpuset: "8"
        devices:
        - /dev/dri/renderD128
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /mnt/Volume1/data:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/video-qsv-vp9-encoder --name=ptg-left.i420 --width=2048 --height=1536 --gop=127 --bitrate=3216 --ip-period=17 --init-qp=41 --qpmin=3 --qpmax=4 --disable-frame-skip=1 --diff-qp-ip=48 --diff-qp-ib=28 --num-ref-frame=9 --rc-mode=1 --reference-mode=0 --cid=106 --id=4"
        runtime: runc


    ###########################################################################
    # Right PtGrey camera.
    device-camera-ptgrey-amd64-right:
        container_name: dlv-ptgrey-right
        image: ptgrey:v3
        #build:
        #    context: https://github.com/chalmers-revere/opendlv-device-camera-spinnaker.git
        #    dockerfile: Dockerfile.amd64
        cpuset: "10"
        restart: always
        network_mode: "host"
        ipc: "host"
        volumes:
        - /mnt/Volume1/data:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -8 /usr/bin/opendlv-device-camera-spinnaker --camera=19074539 --width=2048 --height=1536 --fps=15 --name.i420=ptg-right.i420 --name.argb=ptg-right.argb --nocameratimestamp"

    qsv-h264-thumbnail-ptgrey-right:
        container_name: qsv-h264-thumbnail-ptgrey-right
        image: qsv:latest
        depends_on:
        - device-camera-ptgrey-amd64-right
        cpuset: "11"
        devices:
        - /dev/dri/renderD128
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /mnt/Volume1/data:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/video-qsv-h264-encoder --name=ptg-right.i420 --width=2048 --height=1536 --bitrate=3000 --crop.x=704 --crop.y=500 --crop.width=640 --crop.height=480 --downsample=2 --cid=105 --id=2"
        runtime: runc

    nvenc-h264-ll-rec-ptgrey-right:
        container_name: nvenc-h264-ll-rec-ptgrey-right
        #image: chrberger/video-nvenc-h264-recorder-amd64:cuda10-v0.0.2
        image: nvenc-h264:v2
        depends_on:
        - device-camera-ptgrey-amd64-right
        cpuset: "12"
        init: true
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /mnt/Volume1/data:/tmp
        - $HOME/recordings/lossless:/recordings
        - /usr/lib64/libnvcuvid.so.418.56:/usr/lib/x86_64-linux-gnu/libnvcuvid.so.418.56
        - /usr/lib64/libnvidia-encode.so.418.56:/usr/lib/x86_64-linux-gnu/libnvidia-encode.so.418.56
        working_dir: /recordings
        command: "--name=ptg-right.i420 --width=2048 --height=1536 --recsuffix=-ptgrey-right-lossless --remote --cid=106 --id=2"
        runtime: nvidia

    qsv-vp9-ptgrey-right:
        container_name: qsv-vp9-right
        image: qsv-vp9:v0.0.1
        depends_on:
        - device-camera-ptgrey-amd64-right
        cpuset: "12"
        devices:
        - /dev/dri/renderD128
        restart: always
        ipc: "host"
        network_mode: "host"
        volumes:
        - /mnt/Volume1/data:/tmp
        cap_add:
        - SYS_NICE
        entrypoint: ""
        command: "nice -n -7 /usr/bin/video-qsv-vp9-encoder --name=ptg-right.i420 --width=2048 --height=1536 --gop=127 --bitrate=3216 --ip-period=17 --init-qp=41 --qpmin=3 --qpmax=4 --disable-frame-skip=1 --diff-qp-ip=48 --diff-qp-ib=28 --num-ref-frame=9 --rc-mode=1 --reference-mode=0 --cid=106 --id=5"
        runtime: runc

